MediaBundle\Entity\Commentaire:
    type: entity
    table: null
    repositoryClass: MediaBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        utilisateur:
            type: string
            length: 255



    lifecycleCallbacks: {  }



manyToOne:
    commentaire:
      targetEntity: MediaBundle\Entity\Album
      mappedBy: commentaires